### ISSUE TITLE
usage with tokio panics

### ISSUE THREAD

**Issue by adnanjpg** [makarski/gauth-rs#25]
when using this package with tokio runtime and calling `gauth::serv_account::ServiceAccount::from_file`, I have the following error: `thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.',`

## Steps to reproduce
1. create a new rust app using `cargo init gauth-bug`
2. add the package dependency using `cargo add gauth`
3. copy the test file `service-account-key.json` from the package's files and put it in the root of the new rust app
4. call `from_file` like the following:
```rust
gauth::serv_account::ServiceAccount::from_file(
    "service-account-key.json",
    vec!["https://www.googleapis.com/auth/firebase.messaging"],
);
```
5. when running the application this way, it will work without any trouble
6. now, let's add tokio runtime. firstly, add the tokio package using `cargo add tokio`
7. replace the main function with the following:
```rust
#[tokio::main]
async fn main() {
    gauth::serv_account::ServiceAccount::from_file(
        "service-account-key.json",
        vec!["https://www.googleapis.com/auth/firebase.messaging"],
    );
}
```
8. when running the application this was, it will panic with the error message I've provided above

**Comment by adnanjpg** [comment]
as suggested in this [stackoverflow answer](https://stackoverflow.com/a/62536772/12555423), running the `from_file` function on a seperate thread fixes the issue

```
use std::thread;

#[tokio::main]
async fn main() {
    thread::spawn(|| {
        gauth::serv_account::ServiceAccount::from_file(
            "service-account-key.json",
            vec!["https://www.googleapis.com/auth/firebase.messaging"],
        );
    })
    .join()
    .expect("Thread panicked")
}
```

**Comment by makarski** [comment]
@adnanjpg thank you pointing this out. Let me test the scenarios you mentioned and hopefully we can find a good solution. So far I've been using the the serv_account module in this project with tokio runtime https://github.com/makarski/mstream/blob/main/src/cmd/listener.rs#L24-L25. However, the dependency there is `gauth = 0.4` that is using a version of reqwest before async was introduced.

Before the issue is fixed, a version 0.4 will do, as the changes introduced in 0.5 affect the desktop app auth - there i also updated the reqwest client that introduced the issue.

**Comment by makarski** [comment]
Also always looking forward to have a PR opened

**Comment by adnanjpg** [comment]
here's the pr https://github.com/makarski/gauth-rs/pull/26
